inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - "vendor/**/*"
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  AllowSymlinksInCacheRootDirectory: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude:
    - "spec/*"
Layout/LineLength:
  Exclude:
    - "*.gemspec"
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true
Style/ExponentialNotation:
  Enabled: true
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
